### ISSUE TITLE
Do you have a plan to release the source code of this paper?

### ISSUE THREAD

**Issue by huyhoang17** [xuewenyuan/TGRNet#1]
Hi, 
I read the paper and very interested in it
Do you have a plan to release the source code of this paper?
Thank you, hope to see your response soon!

**Comment by xuewenyuan** [comment]
@huyhoang17 I will try my best to release the code in this month. I'm just a little busy these days.

**Comment by huyhoang17** [comment]
@xuewenyuan Thanks in advance!

**Comment by jiangxiluning** [comment]
@xuewenyuan can you share the TableGraph-350k dataset with me?

**Comment by xuewenyuan** [comment]
@jiangxiluning 感谢关注，代码、实验数据都会pub，最迟不过国庆假期

**Comment by xuewenyuan** [comment]
@huyhoang17 @jiangxiluning The source code has been updated.
