### ISSUE TITLE
作者方便提供一下预训练模型吗？

### ISSUE THREAD

**Issue by zhangtao1234567** [xuewenyuan/TGRNet#21]
作者您好，调整相关路径之后运行了您的测试脚本没有问题，但是训练时找不到预训练模型，根据您GITHUB上提供的预训练模型地址下载下来的是训练好的pth模型文件，方便提供一下原始的预训练模型吗？
报错是这样的：FileNotFoundError: [Errno 2] No such file or directory: './checkpoints/cmdd_overall/prt_net_Backbone.pth'
方便提供这个prt_net_Backbone.pth文件吗？

**Comment by xuewenyuan** [comment]
把best开头的预训练模型改成prt开头就好了
