### ISSUE TITLE
环境同步后，Lloc各项结果还是接近于0

### ISSUE THREAD

**Issue by zdmwang** [xuewenyuan/TGRNet#22]
@EmperorKaiser 谢谢。
@hsdjkfnsfc 抱歉回复比较晚。我在cuda10.2下复现了你的问题，但是切换到cuda9.2后，结果正常。所以，很可能是不同cuda版本下，软件的影响，特别时torch geometric。
我的测试环境：
- cuda 9.2
- torch 1.7.0+torchvision 0.8.0
- torch-cluster 1.5.9
- torch-geometric 1.6.3
- torch-scatter 2.0.6
- torch-sparse 0.6.9
- torch-spline-conv 1.2.1

_Originally posted by @xuewenyuan in https://github.com/xuewenyuan/TGRNet/issues/2#issuecomment-972423748_

**Comment by zdmwang** [comment]
环境同步之后，torch                      1.7.0+cu92
torch-cluster              1.5.9
torch-geometric            1.6.3
torch-model-archiver       0.7.1
torch-scatter              2.0.6
torch-sparse               0.6.9
torch-spline-conv          1.2.1

**Comment by zdmwang** [comment]
环境同步后，Lloc各项指标还是接近于0，测试环境为：
- torch 1.7.0+cu92
- torchvision  0.8.1+cu92
- torch-cluster  1.5.9
- torch-geometric  1.6.3
- torch-model-archiver  0.7.1
- torch-scatter  2.0.6
- torch-sparse  0.6.9
- torch-spline-conv  1.2.1
test_tablegraph-24k最终结果是：
IoU: 0.500, Sloc, Recall: 0.9224, Precision: 0.9086, Hmean(F1): 0.9155
IoU: 0.500, Lloc, Acc_all: 0.0000, Acc_rowSt: 0.0099, Acc_rowEd: 0.0140, Acc_colSt: 0.0199, Acc_colEd: 0.0047
IoU: 0.500, F(beta=0.5): 0.000

**Comment by zdmwang** [comment]
环境同步后，Lloc各项指标还是接近于0，测试环境为：
- torch 1.7.0+cu92
- torchvision  0.8.1+cu92
- torch-cluster  1.5.9
- torch-geometric  1.6.3
- torch-model-archiver  0.7.1
- torch-scatter  2.0.6
- torch-sparse  0.6.9
- torch-spline-conv  1.2.1
test_tablegraph-24k最终结果是：
IoU: 0.500, Sloc, Recall: 0.9224, Precision: 0.9086, Hmean(F1): 0.9155
IoU: 0.500, Lloc, Acc_all: 0.0000, Acc_rowSt: 0.0099, Acc_rowEd: 0.0140, Acc_colSt: 0.0199, Acc_colEd: 0.0047
IoU: 0.500, F(beta=0.5): 0.000

**Comment by xuewenyuan** [comment]
@zdmwang 仅提供这些信息，我很难帮助到你，建议你check中间结果，或者重新训练一个模型
