### ISSUE TITLE
Cell Logistic Location的各项指标几乎为0

### ISSUE THREAD

**Issue by lxq0204** [xuewenyuan/TGRNet#5]
作者您好，我在运行test文件时，Cell Spatial Location可以复现论文中的结果，但是 Cell Logistic Location各项指标几乎为0，请问这是什么原因啊？我用的配置是：cuda 10.1，其余配置均和readme一样。
![image](https://user-images.githubusercontent.com/30117065/144852531-bee30cba-8a2f-4c5b-bf68-4d45cf629fc9.png)

**Comment by xuewenyuan** [comment]
应该还是环境的原因。请参考下面回复中的环境配置再试一试。如果不方便切换conda，就只能再重新训练一下了。
#2

**Comment by lxq0204** [comment]
谢谢回复！那重新训练的方式可否说一下？

**Comment by xuewenyuan** [comment]
> 
我这周更新一下readme吧，根据train.sh的那几个脚本应该是可以直接跑起来的

**Comment by lxq0204** [comment]
> 我这周更新一下readme吧，根据train.sh的那几个脚本应该是可以直接跑起来的
所有从头训练的话，需要多长时间？

**Comment by tarv33** [comment]
@xuewenyuan 发现是torch-geometric版本的问题，目前自动安装的是2.0.2（Lloc结果失败了），但如果安装的是1.6.3是成功了

**Comment by xuewenyuan** [comment]
@somewhat998 感谢反馈

**Comment by lxq0204** [comment]
![image](https://user-images.githubusercontent.com/30117065/145413060-8ee28b75-b587-4bb8-b01a-f02c0c2a0a7f.png)
想问作者，这个查看训练情况的网址怎么打不开呢？加上端口8098也是打不开~

**Comment by xuewenyuan** [comment]
@15954901375 哦，因为我基本用不到，就没启用，你可以参考[cyclegan](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix)的代码修改一下
